name: Release

on:
  push:
    tags: [ 'v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  trivy:
    uses: "./.github/workflows/common-trivy.yaml"
    with:
      export-csv: true

  codeql:
    uses: "./.github/workflows/common-codeql.yaml"
    with:
      export-report: true
