name: Verify
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: make test

    - name: Codecov report
      run: bash <(curl -s https://codecov.io/bash)
